version: "3.9"

volumes:
  laravel-docker-db-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-docker-app
    ports:
      - "8080:8000"
    working_dir: /var/www/html
    depends_on:
      - db
    command:
      - php artisan serve --host=0.0.0.0 --port=8000
  db:
    image: mysql:8.0
    container_name: laravel-docker-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_USER: laravel
    volumes:
      - laravel-docker-db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: laravel
    depends_on:
      - db